[package]
name = "_07"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file_reader = { path = "../common/file_reader" }
itertools = "0.12.0"
